ALTER TABLE duels DROP CONSTRAINT IF EXISTS chk_duels_status;

ALTER TABLE duels ADD CONSTRAINT chk_duels_status
    CHECK (status IN ('WAITING', 'MATCHED', 'IN_PROGRESS', 'EVALUATING', 'COMPLETED', 'CANCELLED', 'DRAW'));
