import { LeaderboardEntry, Page } from '../../core/services/leaderboard.service';

export const LEADERBOARD_PLAYERS_MOCK: LeaderboardEntry[] = [
  {
    rank: 1,
    username: 'NyxCipher',
    avatarUrl: null,
    league: 'LEGEND',
    tone: 'league-legend',
    mark: 'L',
    elo: 4215,
    wins: 21,
    losses: 5,
    winStreak: 2,
    totalDuels: 26,
    winRate: '81%',
  },
  {
    rank: 2,
    username: 'HexNova',
    avatarUrl: null,
    league: 'LEGEND',
    tone: 'league-legend',
    mark: 'L',
    elo: 4178,
    wins: 17,
    losses: 5,
    winStreak: 1,
    totalDuels: 22,
    winRate: '76%',
  },
  {
    rank: 3,
    username: 'OrbitNull',
    avatarUrl: null,
    league: 'MASTER',
    tone: 'league-master',
    mark: 'M',
    elo: 3500,
    wins: 15,
    losses: 2,
    winStreak: 3,
    totalDuels: 17,
    winRate: '88%',
  },
  {
    rank: 4,
    username: 'ShardPulse',
    avatarUrl: null,
    league: 'MASTER',
    tone: 'league-master',
    mark: 'M',
    elo: 3050,
    wins: 15,
    losses: 6,
    winStreak: 2,
    totalDuels: 21,
    winRate: '71%',
  },
  {
    rank: 5,
    username: 'VantaLoop',
    avatarUrl: null,
    league: 'GOLD',
    tone: 'league-gold',
    mark: 'G',
    elo: 2800,
    wins: 12,
    losses: 7,
    winStreak: 0,
    totalDuels: 19,
    winRate: '63%',
  },
  {
    rank: 6,
    username: 'IonDrift',
    avatarUrl: null,
    league: 'GOLD',
    tone: 'league-gold',
    mark: 'G',
    elo: 2100,
    wins: 13,
    losses: 5,
    winStreak: 2,
    totalDuels: 18,
    winRate: '72%',
  },
  {
    rank: 7,
    username: 'QuartzByte',
    avatarUrl: null,
    league: 'SILVER',
    tone: 'league-silver',
    mark: 'S',
    elo: 1800,
    wins: 14,
    losses: 6,
    winStreak: 2,
    totalDuels: 20,
    winRate: '70%',
  },
  {
    rank: 8,
    username: 'PixelRook',
    avatarUrl: null,
    league: 'SILVER',
    tone: 'league-silver',
    mark: 'S',
    elo: 1100,
    wins: 11,
    losses: 5,
    winStreak: 1,
    totalDuels: 16,
    winRate: '69%',
  },
  {
    rank: 9,
    username: 'SilverStack',
    avatarUrl: null,
    league: 'BRONZE',
    tone: 'league-bronze',
    mark: 'B',
    elo: 900,
    wins: 10,
    losses: 5,
    winStreak: 0,
    totalDuels: 15,
    winRate: '67%',
  },
  {
    rank: 10,
    username: 'EchoForge',
    avatarUrl: null,
    league: 'BRONZE',
    tone: 'league-bronze',
    mark: 'B',
    elo: 450,
    wins: 8,
    losses: 6,
    winStreak: 0,
    totalDuels: 14,
    winRate: '57%',
  },
];

export const MOCK_LEADERBOARD_PAGE: Page<LeaderboardEntry> = {
  content: LEADERBOARD_PLAYERS_MOCK,
  totalElements: LEADERBOARD_PLAYERS_MOCK.length,
  totalPages: 1,
  size: 50,
  number: 0,
};